# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 112c147062c2695a55a81b99d8dfd46050152dfa13e144d2bdec63316a0f0379faf4812ab81b08b686205d400ce8b3f3c506cead18696492b656992137d4e7ed

test:
  secret_key_base: d073f2fdc16879060009bcc4a044f35ad9553a771d190c52543bbd52bc88b105b68f9e503da84018a2e59ffc292c7507b0d7887e4ae2e8efe8ac8e10f584644c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
